#!/bin/bash
# Author: Sofiane DJERBI (@Kugge)
# Dependency: spotify-tui
# Used by Spotifyd: Save song to a text file
# So it can be accessed by any app. (Polybar)

# Parse song name
spt_song=$(spt playback -f "%t - %a")
 
# If not empty, send it to song.txt
if [ ! -z "$spt_song" ]; then
    echo $spt_song > ~/.config/spotifyd/song.txt
fi

