#!/bin/sh
# Author: Sofiane DJERBI (@Kugge)

#########################
# START NEEDED SOFTWARE #
#########################

# sxhkd: keyboard shortcuts
pgrep -x sxhkd > /dev/null || sxhkd &

# polybar: dynamic bar
pgrep -x polybar > /dev/null || .config/polybar/launch_polybar -l=trace &

# spotifyd: spotify daemon
pgrep -x spotifyd > /dev/null || spotifyd &

# feh: wallpaper
#feh --bg-fill $HOME/.config/wallpaper.png

# xsetroot: Solid wallpaper
xsetroot -solid "#FFEBF3"

#picom: transparency
#pgrep -x picom > /dev/null || picom --experimental-backends --daemon

# Echo song status in song file
echo "Welcome, user! Happy day ~" \
    > $HOME/.config/spotifyd/song.txt

#################
# LAYOUT CONFIG #
#################

# Screen names
bspc monitor -d 0 1 2 3 4 5 6 7 8 9
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#################
# WINDOW CONFIG #
#################

# Colors
bspc config focused_border_color "#C8CFF3"
bspc config active_border_color  "#C8CFF3"
bspc config normal_border_color  "#C8CFF3"

# Sizes
bspc config border_width         0
bspc config window_gap           10

# Check pointer motion interval, fix alacritty bugs
bspc config pointer_motion_interval 50ms

##############
# APP CONFIG #
##############

# peek: record gif (floating by default)
bspc rule -a Peek state=floating

# Browser to desktop 2
bspc rule -a qutebrowser desktop='^2'

# Discord to desktop 3
bspc rule -a discord desktop='^3'

