#!/bin/sh
# Author: Sofiane DJEBI

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

polybar -rq main --config=~/.config/polybar/config.ini > /dev/null 2>&1 &

echo "Polybar launched"

